bsc_testnet_rpc_url = "https://data-seed-prebsc-1-s1.binance.org:8545"
flametrace_performance = true
[chains]
"97" = { name = "BSC_TESTNET", rpc_url = "https://data-seed-prebsc-1-s1.binance.org:8545" }
"56" = { name = "BSC_TESTNET", rpc_url = "https://bsc-dataseed.binance.org" }
